### ISSUE TITLE
master 分支上有可以正式发布的新tag(release)吗?

### ISSUE THREAD

**Issue by kaka19ace** [henrylee2cn/aster#4]
目前我们依赖了 master较新的提交, struct.go Tags Flush 方法, 用 go mod 下载指定了 v0.4.0
go mod 不支持已有tag 体系的项目里指定最新的 commit 

https://github.com/golang/go/issues/27947

**Comment by henrylee2cn** [comment]
已打新tag v0.5.0，解决此问题
